# Generated by Django 5.0.4 on 2024-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0017_alter_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
